# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeter', '0002_auto_20160205_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
